export const GET_SEARCH_RECIPE = 'GET_SEARCH_RECIPE';
export const GET_RECIPE = 'GET_RECIPE';
export const RECIPE_ERROR = 'RECIPE_ERROR';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const PREVIOUS_PAGE = 'PREVIOUS_PAGE';
export const NEXT_PAGE = 'NEXT_PAGE';
